# Generated by Django 4.2.26 on 2025-11-06 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('secret', models.CharField(max_length=255)),
                ('events', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('timeout_s', models.PositiveIntegerField(default=10)),
                ('max_retries', models.PositiveIntegerField(default=5)),
                ('backoff_s', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_config', to='tenants.tenant')),
            ],
            options={
                'db_table': 'webhook_configs',
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=64)),
                ('url', models.URLField()),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('ok', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='webhooks.webhookconfig')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='tenants.tenant')),
            ],
            options={
                'db_table': 'webhook_deliveries',
                'indexes': [models.Index(fields=['tenant', 'event', 'created_at'], name='webhook_del_tenant__38835b_idx'), models.Index(fields=['created_at'], name='webhook_del_created_50111d_idx')],
            },
        ),
    ]
