# Generated by Django 4.2.26 on 2025-11-06 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantLimitOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_minute', models.PositiveIntegerField(blank=True, null=True)),
                ('per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('quotas_override', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limits_override', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_limit_overrides',
            },
        ),
    ]
