# Generated by Django 4.2.26 on 2025-11-06 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, max_length=64)),
                ('job_id', models.CharField(blank=True, max_length=64, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('billed', models.BooleanField(default=True)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='tenants.tenant')),
            ],
            options={
                'db_table': 'usage_events',
                'indexes': [models.Index(fields=['tenant', 'module', 'created_at'], name='usage_event_tenant__502b4b_idx'), models.Index(fields=['tenant', 'created_at'], name='usage_event_tenant__eaf2d8_idx')],
            },
        ),
    ]
