# Generated by Django 4.2.26 on 2025-11-06 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('per_minute', models.PositiveIntegerField(default=60)),
                ('per_day', models.PositiveIntegerField(default=50000)),
                ('quotas', models.JSONField(blank=True, default=dict)),
                ('unit_prices', models.JSONField(blank=True, default=dict)),
                ('sla', models.CharField(blank=True, default='', max_length=32)),
                ('region', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('country_code', models.CharField(blank=True, default='', max_length=2)),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('webhook_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_usage_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='tenants.plan')),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['-created_at'],
            },
        ),
    ]
