# Generated by Django 4.2.26 on 2025-11-06 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('key_secret_hash', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('allowed_ips', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='tenants.tenant')),
            ],
            options={
                'db_table': 'api_keys',
                'indexes': [models.Index(fields=['tenant', 'active'], name='api_keys_tenant__a0791e_idx')],
            },
        ),
    ]
